stages:
  - build
  - test
  - publish

default:
  before_script:
    #
    # show all the environment variables.
    - |
      Get-ChildItem env: `
        | Format-Table -AutoSize `
        | Out-String -Width 4096 -Stream `
        | ForEach-Object {$_.Trim()}

build:
  stage: build
  tags:
    - vs2022
  script:
    - ./build.ps1 build
  artifacts:
    expire_in: 1 week
    paths:
      - packages
      - ExampleApplication/bin

test:
  stage: test
  tags:
    - vs2022
  dependencies:
    - build
  script:
    - ./build.ps1 test
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# publish the package to the GitLab project repository.
# see https://docs.gitlab.com/ee/user/packages/nuget_repository/index.html#publish-a-nuget-package-by-using-cicd
publish:
  stage: publish
  tags:
    - vs2022
  dependencies:
    - test
  script:
    - ./build.ps1 publish
