stages:
  - build
  - test
  - publish

default:
  before_script:
    #
    # show the entire job script (GitLab concatenates all the before_script lines
    # and all the job script lines into a single file and executes it with
    # PowerShell).
    - |
      Write-Output "$PSCommandPath content:"
      Get-Content $PSCommandPath
    #
    # show all the environment variables.
    - |
      Get-ChildItem env: `
        | Format-Table -AutoSize `
        | Out-String -Width 4096 -Stream `
        | ForEach-Object {$_.Trim()}

build_job:
  stage: build
  tags:
    - vs2022
  script:
    - ./build.ps1 build
  artifacts:
    expire_in: 1 week
    paths:
      - 'ExampleLibrary/ExampleLibrary.*.nupkg'
      - 'ExampleApplication/bin'

test_job:
  stage: test
  tags:
    - vs2022
  dependencies:
    - build_job
  script:
    - ./build.ps1 test
  artifacts:
    expire_in: 1 week
    paths:
      - 'ExampleLibrary/ExampleLibrary.*.nupkg'

# publish the package to the GitLab project repository.
# see https://docs.gitlab.com/ee/user/packages/nuget_repository/index.html#publish-a-nuget-package-by-using-cicd
publish_job:
  stage: publish
  only:
    - gitlab
  tags:
    - vs2022
  dependencies:
    - test_job
  script:
    - ./build.ps1 publish
